### ISSUE TITLE
The application crashed when I launch it

### ISSUE THREAD

**Issue by petro-zdebskyi** [jacsmith21/todo#1]
The build was successful, but the application crashed when I launch it on a device or on a virtual device.

**Comment by jsmith** [comment]
Are you running using Android studio 2.3.1? I haven't worked on this project for a while now and there are much newer versions of Android studio that have been released

**Comment by petro-zdebskyi** [comment]
I am using Android Studio 3.1. I made a couple of changes, so it runs well. I can make pull request with fixes if needed.

**Comment by jsmith** [comment]
That would be great honestly :100: I'd love to keep this app running on newer versions

**Comment by petro-zdebskyi** [comment]
I remembered that I had to make a pull request, but now I cannot find this project on my computer. Sorry for that, I close this issue.

**Comment by jsmith** [comment]
Thanks fine, thanks anyway!
